/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exa_1;

import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author jason
 */
public class Biblioteca_Virtual extends javax.swing.JFrame {

    /**
     * Creates new form Biblioteca_Virtual
     */
    public Biblioteca_Virtual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_Usaurio_Administrador = new javax.swing.JButton();
        bt_Usuario_Biblioteca = new javax.swing.JButton();
        bt_Creacion_Usuario = new javax.swing.JButton();
        bt_Historail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log in");

        bt_Usaurio_Administrador.setText("Usuario Administrador");
        bt_Usaurio_Administrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Usaurio_AdministradorMouseClicked(evt);
            }
        });

        bt_Usuario_Biblioteca.setText("Usuario Biblioteca");
        bt_Usuario_Biblioteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Usuario_BibliotecaMouseClicked(evt);
            }
        });

        bt_Creacion_Usuario.setText("Creacion de un Usuario");
        bt_Creacion_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Creacion_UsuarioMouseClicked(evt);
            }
        });

        bt_Historail.setText("Historial");
        bt_Historail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_HistorailMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_Creacion_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bt_Usaurio_Administrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_Usuario_Biblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(bt_Historail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(bt_Usaurio_Administrador)
                .addGap(57, 57, 57)
                .addComponent(bt_Usuario_Biblioteca)
                .addGap(45, 45, 45)
                .addComponent(bt_Creacion_Usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(bt_Historail)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_Usaurio_AdministradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Usaurio_AdministradorMouseClicked
        // TODO add your handling code here:
        Usuario_Administrador A = new Usuario_Administrador();
        A.setLocationRelativeTo(this);
        A.pack();
        String usuario = JOptionPane.showInputDialog(this, "Ingrese usuario");
        String contraseña = JOptionPane.showInputDialog(this, "Contraseña de usuario");
        if (usuario.equalsIgnoreCase(this.usuario.get(cont).getNombre_u()) && contraseña.equalsIgnoreCase(this.usuario.get(cont).getContraseña())) {
            histori.add("Login de un usuario ad ministrador de la biblioteca virtual");
            A.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Usuario Administrador no valido");
        }
    }//GEN-LAST:event_bt_Usaurio_AdministradorMouseClicked

    private void bt_Usuario_BibliotecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Usuario_BibliotecaMouseClicked
        // TODO add your handling code here:
        Usuario u = new Usuario();
        u.setLocationRelativeTo(this);
        u.pack();
        String usuario = JOptionPane.showInputDialog(this, "Ingrese usuario");
        String contraseña = JOptionPane.showInputDialog(this, "Contraseña de usuario");
        if (usuario.equalsIgnoreCase(this.usuario.get(cont).getNombre_u()) && contraseña.equalsIgnoreCase(this.usuario.get(cont).getContraseña())) {
            histori.add("Login de un usuario de la biblioteca virtual");
            u.setVisible(true);
            cont++;
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no valido o no existente");
        }
    }//GEN-LAST:event_bt_Usuario_BibliotecaMouseClicked

    private void bt_Creacion_UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Creacion_UsuarioMouseClicked
        // TODO add your handling code here:
        String genero_f = "", nombre_u = "", contraseña = "", numero_t = "", correo = "", nombre_c = "";
        int op = Integer.parseInt(JOptionPane.showInputDialog(this, "1. Usuario\n2. Usuario Administrador\nIngrese una opcion de creacion del usuario"));
        Date fecha_nace = new Date();
        switch (op) {
            case 1:

                nombre_u = JOptionPane.showInputDialog(this, "Ingrese usuario");
                contraseña = JOptionPane.showInputDialog(this, "Contraseña de usuario");
                fecha_nace = new Date();
                numero_t = JOptionPane.showInputDialog(this, "Ingrese su numero de telefono");
                correo = JOptionPane.showInputDialog(this, "Ingrese su correo electronico");
                nombre_c = JOptionPane.showInputDialog(this, "Ingrese su nombre completo");
                usuario.add(new Usuarios(nombre_u, contraseña, fecha_nace, numero_t, correo, nombre_c, ""));
                histori.add("Se cro un nuevo usuario Administrador");
                break;
            case 2:
                nombre_u = JOptionPane.showInputDialog(this, "Ingrese usuario");
                contraseña = JOptionPane.showInputDialog(this, "Contraseña de usuario");
                fecha_nace = new Date();
                numero_t = JOptionPane.showInputDialog(this, "Ingrese su numero de telefono");
                correo = JOptionPane.showInputDialog(this, "Ingrese su correo electronico");
                nombre_c = JOptionPane.showInputDialog(this, "Ingrese su nombre completo");
                int genero = Integer.parseInt(JOptionPane.showInputDialog(this, "1. Fantasia\n2. Romance\n3. Accion\n4. Historia\nIngrese una opcion como su genero favorito"));
                switch (genero) {
                    case 1:
                        genero_f = "Fantasia";
                        break;
                    case 2:
                        genero_f = "Romance";
                        break;
                    case 3:
                        genero_f = "Accion";
                        break;
                    case 4:
                        genero_f = "Histario";
                        break;
                    default:
                        JOptionPane.showMessageDialog(this, "Tipo de genero favorito no valido");
                        break;
                }//Fin del case de los libros
                usuario.add(new Usuarios(nombre_u, contraseña, fecha_nace, numero_t, correo, nombre_c, genero_f));
                histori.add("Se cro un nuevo usuario de la biblioteca");
                break;
            default:
                JOptionPane.showMessageDialog(this, "Opcion de creacion no valida");
        }//Fin del case de la opion de creacion de usuario
    }//GEN-LAST:event_bt_Creacion_UsuarioMouseClicked

    private void bt_HistorailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_HistorailMouseClicked
        // TODO add your handling code here:
        for (int i = 0; i < histori.size(); i++) {
            System.out.println(histori.get(i));
        }
    }//GEN-LAST:event_bt_HistorailMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biblioteca_Virtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biblioteca_Virtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biblioteca_Virtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biblioteca_Virtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biblioteca_Virtual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Creacion_Usuario;
    private javax.swing.JButton bt_Historail;
    private javax.swing.JButton bt_Usaurio_Administrador;
    private javax.swing.JButton bt_Usuario_Biblioteca;
    // End of variables declaration//GEN-END:variables

    ArrayList<Usuarios> usuario = new ArrayList();
    ArrayList<String> histori = new ArrayList();
    int cont = 0;
}
